export type FinancialData = {
    Index: string;
    'P/E': number;
    'EPS (ttm)': number;
    'Insider Own': number;
    'Shs Outstand': number;
    'Perf Week': number;
    'Market Cap': number;
    'Forward P/E': number;
    'EPS next Y': number;
    'Insider Trans': number;
    'Shs Float': number;
    'Perf Month': number;
    Income: number;
    PEG: number;
    'EPS next Q': number;
    'Inst Own': number;
    'Short Float': number;
    'Perf Quarter': number;
    Sales: number;
    'P/S': number;
    'EPS this Y': number;
    'Inst Trans': number;
    'Short Ratio': number;
    'Perf Half Y': number;
    'Book/sh': number;
    'P/B': number;
    ROA: number;
    'Short Interest': number;
    'Perf Year': number;
    'Cash/sh': number;
    'P/C': number;
    'EPS next 5Y': number;
    ROE: number;
    '52W Range': number;
    'Perf YTD': number;
    'Dividend Est.': string;
    'P/FCF': number;
    'EPS past 5Y': string;
    ROI: number;
    '52W High': number;
    Beta: number;
    'Dividend TTM': string;
    'Quick Ratio': number;
    'Sales past 5Y': number;
    'Gross Margin': Record<string, number | undefined>;
    '52W Low': number;
    'ATR (14)': number;
    'Dividend Ex-Date': string;
    'Current Ratio': number;
    'EPS Y/Y TTM': number;
    'Oper. Margin': number;
    'RSI (14)': number;
    Volatility: number;
    Employees: number;
    'Debt/Eq': number;
    'Sales Y/Y TTM': number;
    'Profit Margin': Record<string, number | undefined>;
    Recom: number;
    'Target Price': number;
    'Option/Short': string;
    'LT Debt/Eq': number;
    'EPS Q/Q': number;
    Payout: number;
    'Rel Volume': number;
    'Prev Close': number;
    'Sales Surprise': number;
    'EPS Surprise': number;
    'Sales Q/Q': number;
    Earnings: string;
    'Avg Volume': number;
    Price: number;
    SMA20: number;
    SMA50: number;
    SMA200: number;
    Trades: string;
    Volume: number;
    Change: number;
    "Net Income": Record<string, number | undefined>;
    "Depreciation & Amortization": Record<string, number | undefined>;
    "Share-Based Compensation": Record<string, number | undefined>;
    "Other Operating Activites": Record<string, number | undefined>;
    "Operating Cash Flow": Record<string, number | undefined>;
    "Operating Cash Flow Growth": Record<string, number | undefined>;
    "Capital Expenditures": Record<string, number | undefined>;
    "Acquisitions": Record<string, number | undefined>;
    "Change in Investments": Record<string, number | undefined>;
    "Other Investing Activities": Record<string, number | undefined>;
    "Investing Cash Flow": Record<string, number | undefined>;
    "Share Issuance / Repurchase": Record<string, number | undefined>;
    "Debt Issued / Paid": Record<string, number | undefined>;
    "Other Financing Activites": Record<string, number | undefined>;
    "Financing Cash Flow": Record<string, number | undefined>;
    "Exchange Rate Effect": Record<string, number | undefined>;
    "Net Cash Flow": Record<string, number | undefined>;
    "Free Cash Flow": Record<string, number | undefined>;
    "Free Cash Flow Growth": Record<string, number | undefined>;
    "Free Cash Flow Margin": Record<string, number | undefined>;
    "Free Cash Flow Per Share": Record<string, number | undefined>;
    "Revenue": Record<string, number | undefined>;
    "Revenue Growth (YoY)": Record<string, number | undefined>;
    "Cost of Revenue": Record<string, number | undefined>;
    "Gross Profit": Record<string, number | undefined>;
    "Selling, General & Admin": Record<string, number | undefined>;
    "Research & Development": Record<string, number | undefined>;
    "Other Operating Expenses": Record<string, number | undefined>;
    "Operating Expenses": Record<string, number | undefined>;
    "Operating Income": Record<string, number | undefined>;
    "Interest Expense / Income": Record<string, number | undefined>;
    "Other Expense / Income": Record<string, number | undefined>;
    "Pretax Income": Record<string, number | undefined>;
    "Income Tax": Record<string, number | undefined>;
    "Net Income Growth": Record<string, number | undefined>;
    "Shares Outstanding (Basic)": Record<string, number | undefined>;
    "Shares Outstanding (Diluted)": Record<string, number | undefined>;
    "Shares Change": Record<string, number | undefined>;
    "EPS (Basic)": Record<string, number | undefined>;
    "EPS (Diluted)": Record<string, number | undefined>;
    "EPS Growth": Record<string, number | undefined>;
    "Operating Margin": Record<string, number | undefined>;
    "Effective Tax Rate": Record<string, number | undefined>;
    "EBITDA": Record<string, number | undefined>;
    "EBITDA Margin": Record<string, number | undefined>;
    "EBIT": Record<string, number | undefined>;
    "EBIT Margin": Record<string, number | undefined>;
    "Cash & Cash Equivalents": Record<string, number | undefined>;
    "Cash Growth": Record<string, number | undefined>;
    "Receivables": Record<string, number | undefined>;
    "Inventory": Record<string, number | undefined>;
    "Other Current Assets": Record<string, number | undefined>;
    "Total Current Assets": Record<string, number | undefined>;
    "Property, Plant & Equipment": Record<string, number | undefined>;
    "Long-Term Investments": Record<string, number | undefined>;
    "Goodwill and Intangibles": Record<string, number | undefined>;
    "Other Long-Term Assets": Record<string, number | undefined>;
    "Total Long-Term Assets": Record<string, number | undefined>;
    "Total Assets": Record<string, number | undefined>;
    "Accounts Payable": Record<string, number | undefined>;
    "Deferred Revenue": Record<string, number | undefined>;
    "Current Debt": Record<string, number | undefined>;
    "Other Current Liabilities": Record<string, number | undefined>;
    'Total Current Liabilities': Record<string, number | undefined>;
    "Long-Term Debt": Record<string, number | undefined>;
    "Other Long-Term Liabilities": Record<string, number | undefined>;
    "Total Long-Term Liabilities": Record<string, number | undefined>;
    "Total Liabilities": Record<string, number | undefined>;
    "Total Debt": Record<string, number | undefined>;
    "Debt Growth": Record<string, number | undefined>;
    "Retained Earnings": Record<string, number | undefined>;
    "Comprehensive Income": Record<string, number | undefined>;
    "Shareholder's Equity": Record<string, number | undefined>;
    "Net Cash / Debt": Record<string, number | undefined>;
    "Net Cash / Debt Growth": Record<string, number | undefined>;
    "Net Cash Per Share": Record<string, number | undefined>;
    "Working Capital": Record<string, number | undefined>;
    "Book Value Per Share": Record<string, number | undefined>;
 };
 
 