type FinancialData = {
    Index: string;
    'P/E': number;
    'EPS (ttm)': number;
    'Insider Own': number;
    'Shs Outstand': number;
    'Perf Week': number;
    'Market Cap': number;
    'Forward P/E': number;
    'EPS next Y': number;
    'Insider Trans': number;
    'Shs Float': number;
    'Perf Month': number;
    Income: number;
    PEG: number;
    'EPS next Q': number;
    'Inst Own': number;
    'Short Float': number;
    'Perf Quarter': number;
    Sales: number;
    'P/S': number;
    'EPS this Y': number;
    'Inst Trans': number;
    'Short Ratio': number;
    'Perf Half Y': number;
    'Book/sh': number;
    'P/B': number;
    ROA: number;
    'Short Interest': number;
    'Perf Year': number;
    'Cash/sh': number;
    'P/C': number;
    'EPS next 5Y': number;
    ROE: number;
    '52W Range': number;
    'Perf YTD': number;
    'Dividend Est.': string;
    'P/FCF': number;
    'EPS past 5Y': string;
    ROI: number;
    '52W High': number;
    Beta: number;
    'Dividend TTM': string;
    'Quick Ratio': number;
    'Sales past 5Y': number;
    'Gross Margin': Record<string, number>;
    '52W Low': number;
    'ATR (14)': number;
    'Dividend Ex-Date': string;
    'Current Ratio': number;
    'EPS Y/Y TTM': number;
    'Oper. Margin': number;
    'RSI (14)': number;
    Volatility: number;
    Employees: number;
    'Debt/Eq': number;
    'Sales Y/Y TTM': number;
    'Profit Margin': Record<string, number>;
    Recom: number;
    'Target Price': number;
    'Option/Short': string;
    'LT Debt/Eq': number;
    'EPS Q/Q': number;
    Payout: number;
    'Rel Volume': number;
    'Prev Close': number;
    'Sales Surprise': number;
    'EPS Surprise': number;
    'Sales Q/Q': number;
    Earnings: string;
    'Avg Volume': number;
    Price: number;
    SMA20: number;
    SMA50: number;
    SMA200: number;
    Trades: string;
    Volume: number;
    Change: number;
    'Net Income': Record<string, number>;
    'Depreciation & Amortization': Record<string, number>;
    'Share-Based Compensation': Record<string, number>;
    'Other Operating Activities': Record<string, number>;
    'Operating Cash Flow': Record<string, number>;
    'Operating Cash Flow Growth': Record<string, number | undefined>;
    'Capital Expenditures': Record<string, number>;
    Acquisitions: Record<string, number>;
    'Change in Investments': Record<string, number>;
    'Other Investing Activities': Record<string, number | undefined>;
    'Investing Cash Flow': Record<string, number>;
    'Share Issuance / Repurchase': Record<string, number>;
    'Debt Issued / Paid': Record<string, number>;
    'Other Financing Activities': Record<string, number>;
    'Financing Cash Flow': Record<string, number>;
    'Exchange Rate Effect': Record<string, number>;
    'Net Cash Flow': Record<string, number>;
    'Free Cash Flow': Record<string, number>;
    'Free Cash Flow Growth': Record<string, number | undefined>;
    'Free Cash Flow Margin': Record<string, number>;
    'Free Cash Flow Per Share': Record<string, number>;
    'Revenue Growth (YoY)': Record<string, number>;
    'Cost of Revenue': Record<string, number>;
    'Gross Profit': Record<string, number>;
    'Selling, General & Admin': Record<string, number>;
    'Research & Development': Record<string, number>;
    'Other Operating Expenses': Record<string, number>;
    'Operating Expenses': Record<string, number>;
    'Operating Income': Record<string, number>;
    'Interest Expense / Income': Record<string, number>;
    'Other Expense / Income': Record<string, number>;
    'Pretax Income': Record<string, number>;
    'Income Tax': Record<string, number>;
    'Net Income Growth': Record<string, number | undefined>;
    'Shares Outstanding (Basic)': Record<string, number>;
    'Shares Outstanding (Diluted)': Record<string, number>;
    'Shares Change': Record<string, number>;
    'Shares Split Ratio': Record<string, string>;
    'Book Value Per Share': Record<string, number>;
  };
  